name: Build Apk

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: kaisugi/action-regex-match@v1.0.0
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^v[0-9]+\.[0-9]+\.[0-9]+$'

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        working-directory: ./ShatterpointSandbox
        run: chmod +x gradlew
          
      - name: Build
        working-directory: ./ShatterpointSandbox
        run:
          ./gradlew assembleRelease

      - name: Move files
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          mv ShatterpointSandbox/app/build/outputs/apk/release/app-release-unsigned.apk ShatterpointSandbox/app/build/outputs/app-release.apk

      - name: Sign App
        if: ${{ steps.regex-match.outputs.match != '' }}
        id: sign_app
        uses: ilharp/sign-android-release@v1.0.4
        with:
          releaseDir: Shatterpoint/app/build/outputs
          signingKey: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.RELEASE_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_SIGNING_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_SIGNING_PASSWORD }}

      - name: Check files
        working-directory: ./ShatterpointSandbox
        run: ls -al app/build/outputs/apk/release

      - name: Upload aab and apk
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./**/ShatterpointSandbox/app/build/outputs/*.apk
