name: Build Apk

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./ShatterpointSandbox
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./ShatterpointSandbox
        run: ./gradlew build
          
      - name: Sign and Build Release Bundle
        working-directory: ./ShatterpointSandbox
        run:
          ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ShatterpointSandbox/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          alias: ${{ secrets.RELEASE_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_SIGNING_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_SIGNING_PASSWORD }}

      - name: Check files
        working-directory: ./ShatterpointSandbox
        run: ls -al app/build/outputs/apk/release

      - name: Upload aab and apk
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./**/app/build/outputs/apk/release/*.apk
