name: Build Apk

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup kstf
        run: |
          echo "${{ secrets.KSTF }}" > shatterpointhelper.keystore.asc
          gpg -d --passphrase "${{ secrets.GPGP }}" --batch shatterpointhelper.keystore.asc > shatterpointhelper.keystore

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./ShatterpointSandbox
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./ShatterpointSandbox
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          
      - name: Build release APK
        working-directory: ./ShatterpointSandbox
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Check files
        working-directory: ./ShatterpointSandbox
        run: ls -al app/build/outputs/apk/release

      - name: Upload aab and apk
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./**/app/build/outputs/apk/release/*.apk
