name: Build Apk

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./ShatterpointSandbox
        run: chmod +x gradlew

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          working-directory: ./ShatterpointSandbox
          fileName: 'keystore/your_signing_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build with Gradle
        working-directory: ./ShatterpointSandbox
        run: ./gradlew build
          
      - name: Build release APK
        working-directory: ./ShatterpointSandbox
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_SIGNING_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_SIGNING_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run:
          ./gradlew assembleRelease

      - name: Check files
        working-directory: ./ShatterpointSandbox
        run: ls -al app/build/outputs/apk/release

      - name: Upload aab and apk
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./**/app/build/outputs/apk/release/*.apk
